server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: qwerty
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true




#########log4j(这里可以不做指定  除非自己重新命名)##########
logging:
  config: classpath:log4j.xml
##系统变量信息
com:
  alan:
    title: Alan dev
    socketUrl: localhost
    socketPort: 8888